name: mmtf-genomics

channels:
  - anaconda
  - conda-forge

dependencies:
  - python>=3.6
  - openjdk==8.0.152
  - pyspark==2.3.2
  - biopython==1.72
  - pip:
      - jupyter_contrib_nbextensions  
      - mmtf-pyspark==0.3.5
